apiVersion: v1
kind: Namespace
metadata:
  name: openshift-sriov-network-operator
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-sriov
  namespace: openshift-sriov-network-operator
  annotations:
    apps.open-cluster-management.io/git-path: cluster_configuration/sites/sample_site/sriov
spec:
  channel: flexran-workloads/acm-gitops-github
  name: flexran-sriov
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-sriov-to-ready-clusters
