apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-nfd
  namespace: openshift-nfd
  annotations:
    apps.open-cluster-management.io/git-path: cluster_configuration/sites/sample_site/nfd
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: flexran-workloads/acm-gitops-github
  name: flexran-nfd
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-nfd-to-ready-clusters
