apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-multus-to-ready-clusters
  namespace: multus-networks
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
