apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-performance-to-ready-clusters
  namespace: openshift-performance-addon
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
