apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-ptp-to-ready-clusters
  namespace: openshift-ptp
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
