apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-sriov-to-ready-clusters
  namespace: openshift-sriov-network-operator
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
