---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-configuration
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: cluster-configuration-policy
  namespace: default
placementRef:
  name: cluster-configuration-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: cluster-configuration-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster-configuration-rule
  namespace: default
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
