apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-gitops-github
  namespace: flexran-workloads
spec:
  type: Git
  pathname: https://github.com/redhat-nfvpe/flexran-manifests.git
