apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-performance-addon-operatorgroup
  namespace: openshift-performance-addon
spec:
  targetNamespaces:
  - openshift-performance-addon
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator-subscription
  namespace: openshift-performance-addon
spec:
  channel: "4.5"
  name: performance-addon-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
