apiVersion: v1
kind: Namespace
metadata:
  labels:
          openshift.io/run-level: "1"
  name: openshift-ptp
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ptp-operators
  namespace: openshift-ptp
spec:
  targetNamespaces:
  - openshift-ptp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ptp-operator-subscription
  namespace: openshift-ptp
spec:
  channel: "4.4"
  name: ptp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
