apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: apply-nfd-to-ready-clusters
  namespace: openshift-nfd
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
