apiVersion: v1
kind: Namespace
metadata:
  name: multus-networks
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-multus-networks
  namespace: multus-networks
  annotations:
    apps.open-cluster-management.io/git-path: cluster_configuration/sites/sample_site/multus
spec:
  channel: flexran-workloads/acm-gitops-github
  name: flexran-multus-networks
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-multus-to-ready-clusters
