apiVersion: v1
kind: Namespace
metadata:
  name: openshift-performance-addon
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-performance
  namespace: openshift-performance-addon
  annotations:
    apps.open-cluster-management.io/git-path: cluster_configuration/sites/sample_site/performance_profile/
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: flexran-workloads/acm-gitops-github
  name: flexran-performance
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-performance-to-ready-clusters
