apiVersion: v1
kind: Namespace
metadata:
  name: openshift-ptp
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: flexran-ptp
  namespace: openshift-ptp
  annotations:
    apps.open-cluster-management.io/git-path: cluster_configuration/sites/sample_site/ptp
spec:
  channel: flexran-workloads/acm-gitops-github
  name: flexran-ptp
  placement:
    placementRef:
      kind: PlacementRule
      name: apply-ptp-to-ready-clusters
