apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-network
  namespace: openshift-sriov-network-operator 
spec:
  ipam: '{
    "type": "static",
    "addresses": [ { "address": "10.56.217.1/24" } ]
  }'
  capabilities: '{"mac": true, "ips": true}' 
  resourceName: sriov_net1
